#ifndef ZGLOBALS_H
#define ZGLOBALS_H

#include "../Core/x/xGlobals.h"
#include "../Core/x/xShadowSimple.h"
#include "../Core/x/xEntDrive.h"

#include "zEnt.h"
#include "zEntPlayer.h"
#include "zScene.h"

struct zGlobalSettings
{
    unsigned short AnalogMin;
    unsigned short AnalogMax;
    float SundaeTime;
    float SundaeMult;
    unsigned int InitialShinyCount;
    unsigned int InitialSpatulaCount;
    int ShinyValuePurple;
    int ShinyValueBlue;
    int ShinyValueGreen;
    int ShinyValueYellow;
    int ShinyValueRed;
    int ShinyValueCombo0;
    int ShinyValueCombo1;
    int ShinyValueCombo2;
    int ShinyValueCombo3;
    int ShinyValueCombo4;
    int ShinyValueCombo5;
    int ShinyValueCombo6;
    int ShinyValueCombo7;
    int ShinyValueCombo8;
    int ShinyValueCombo9;
    int ShinyValueCombo10;
    int ShinyValueCombo11;
    int ShinyValueCombo12;
    int ShinyValueCombo13;
    int ShinyValueCombo14;
    int ShinyValueCombo15;
    float ComboTimer;
    unsigned int Initial_Specials;
    unsigned int TakeDamage;
    float DamageTimeHit;
    float DamageTimeSurface;
    float DamageTimeEGen;
    float DamageSurfKnock;
    float DamageGiveHealthKnock;
    unsigned int CheatSpongeball;
    unsigned int CheatPlayerSwitch;
    unsigned int CheatAlwaysPortal;
    unsigned int CheatFlyToggle;
    unsigned int DisableForceConversation;
    float StartSlideAngle;
    float StopSlideAngle;
    float RotMatchMaxAngle;
    float RotMatchMatchTime;
    float RotMatchRelaxTime;
    float Gravity;
    float BBashTime;
    float BBashHeight;
    float BBashDelay;
    float BBashCVTime;
    float BBounceSpeed;
    float BSpinMinFrame;
    float BSpinMaxFrame;
    float BSpinRadius;
    float SandyMeleeMinFrame;
    float SandyMeleeMaxFrame;
    float SandyMeleeRadius;
    float BubbleBowlTimeDelay;
    float BubbleBowlLaunchPosLeft;
    float BubbleBowlLaunchPosUp;
    float BubbleBowlLaunchPosAt;
    float BubbleBowlLaunchVelLeft;
    float BubbleBowlLaunchVelUp;
    float BubbleBowlLaunchVelAt;
    float BubbleBowlPercentIncrease;
    float BubbleBowlMinSpeed;
    float BubbleBowlMinRecoverTime;
    float SlideAccelVelMin;
    float SlideAccelVelMax;
    float SlideAccelStart;
    float SlideAccelEnd;
    float SlideAccelPlayerFwd;
    float SlideAccelPlayerBack;
    float SlideAccelPlayerSide;
    float SlideVelMaxStart;
    float SlideVelMaxEnd;
    float SlideVelMaxIncTime;
    float SlideVelMaxIncAccel;
    float SlideAirHoldTime;
    float SlideAirSlowTime;
    float SlideAirDblHoldTime;
    float SlideAirDblSlowTime;
    float SlideVelDblBoost;
    unsigned char SlideApplyPhysics;
    unsigned char PowerUp[2];
    unsigned char InitialPowerUp[2];
};

struct xEntBoulder;
struct zEntHangable;
struct zPlatform;
struct xSurface;
struct zAssetPickupTable;
struct zCutsceneMgr;

struct zCheckPoint
{
    xVec3 pos;
    float rot;
    unsigned int initCamID;
};

struct zPlayerGlobals
{
    zEnt ent;
    xEntShadow entShadow_embedded;
    xShadowSimpleCache simpShadow_embedded;
    zGlobalSettings g;
    zPlayerSettings* s;
    zPlayerSettings sb;
    zPlayerSettings patrick;
    zPlayerSettings sandy;
    xModelInstance* model_spongebob;
    xModelInstance* model_patrick;
    xModelInstance* model_sandy;
    unsigned int Visible;
    unsigned int Health;
    int Speed;
    float SpeedMult;
    int Sneak;
    int Teeter;
    float SlipFadeTimer;
    int Slide;
    float SlideTimer;
    int Stepping;
    int JumpState;
    int LastJumpState;
    float JumpTimer;
    float LookAroundTimer;
    unsigned int LookAroundRand;
    unsigned int LastProjectile;
    float DecelRun;
    float DecelRunSpeed;
    float HotsauceTimer;
    float LeanLerp;
    float ScareTimer;
    xBase* ScareSource;
    float CowerTimer;
    float DamageTimer;
    float SundaeTimer;
    float ControlOffTimer;
    float HelmetTimer;
    unsigned int WorldDisguise;
    unsigned int Bounced;
    float FallDeathTimer;
    float HeadbuttVel;
    float HeadbuttTimer;
    unsigned int SpecialReceived;
    xEnt* MountChimney;
    float MountChimOldY;
    unsigned int MaxHealth;
    unsigned int DoMeleeCheck;
    float VictoryTimer;
    float BadGuyNearTimer;
    float ForceSlipperyTimer;
    float ForceSlipperyFriction;
    float ShockRadius;
    float ShockRadiusOld;
    float Face_ScareTimer;
    unsigned int Face_ScareRandom;
    unsigned int Face_Event;
    float Face_EventTimer;
    float Face_PantTimer;
    unsigned int Face_AnimSpecific;
    unsigned int IdleRand;
    float IdleMinorTimer;
    float IdleMajorTimer;
    float IdleSitTimer;
    int Transparent;
    zEnt* FireTarget;
    unsigned int ControlOff;
    unsigned int ControlOnEvent;
    unsigned int AutoMoveSpeed;
    float AutoMoveDist;
    xVec3 AutoMoveTarget;
    xBase* AutoMoveObject;
    zEnt* Diggable;
    float DigTimer;
    zPlayerCarryInfo carry;
    zPlayerLassoInfo lassoInfo;
    xModelTag BubbleWandTag[2];
    xModelInstance* model_wand;
    xEntBoulder* bubblebowl;
    float bbowlInitVel;
    zEntHangable* HangFound;
    zEntHangable* HangEnt;
    zEntHangable* HangEntLast;
    xVec3 HangPivot;
    xVec3 HangVel;
    float HangLength;
    xVec3 HangStartPos;
    float HangStartLerp;
    xModelTag HangPawTag[4];
    float HangPawOffset;
    float HangElapsed;
    float Jump_CurrGravity;
    float Jump_HoldTimer;
    float Jump_ChangeTimer;
    int Jump_CanDouble;
    int Jump_CanFloat;
    int Jump_SpringboardStart;
    zPlatform* Jump_Springboard;
    int CanJump;
    int CanBubbleSpin;
    int CanBubbleBounce;
    int CanBubbleBash;
    int IsJumping;
    int IsDJumping;
    int IsBubbleSpinning;
    int IsBubbleBouncing;
    int IsBubbleBashing;
    int IsBubbleBowling;
    int WasDJumping;
    int IsCoptering;
    _zPlayerWallJumpState WallJumpState;
    int cheat_mode;
    unsigned int Inv_Shiny;
    unsigned int Inv_Spatula;
    unsigned int Inv_PatsSock[15];
    unsigned int Inv_PatsSock_Max[15];
    unsigned int Inv_PatsSock_CurrentLevel;
    unsigned int Inv_LevelPickups[15];
    unsigned int Inv_LevelPickups_CurrentLevel;
    unsigned int Inv_PatsSock_Total;
    xModelTag BubbleTag;
    xEntDrive drv;
    xSurface* floor_surf;
    xVec3 floor_norm;
    int slope;
    xCollis earc_coll;
    xSphere head_sph;
    xModelTag center_tag;
    xModelTag head_tag;
    unsigned int TongueFlags[2];
    xVec3 RootUp;
    xVec3 RootUpTarget;
    zCheckPoint cp;
    unsigned int SlideTrackSliding;
    unsigned int SlideTrackCount;
    xEnt* SlideTrackEnt[111];
    unsigned int SlideNotGroundedSinceSlide;
    xVec3 SlideTrackDir;
    xVec3 SlideTrackVel;
    float SlideTrackDecay;
    float SlideTrackLean;
    float SlideTrackLand;
    unsigned char sb_model_indices[14];
    xModelInstance* sb_models[14];
    unsigned int currentPlayer;
    xVec3 PredictRotate;
    xVec3 PredictTranslate;
    float PredictAngV;
    xVec3 PredictCurrDir;
    float PredictCurrVel;
    float KnockBackTimer;
    float KnockIntoAirTimer;
};

struct zGlobals : xGlobals
{
    zPlayerGlobals player;
    zAssetPickupTable* pickupTable;
    zCutsceneMgr* cmgr;
    zScene* sceneCur;
    zScene* scenePreload;
};

#endif