#include "zNPCGoals.h"

#include "zNPCGoalStd.h"
#include "zNPCGoalScript.h"
#include "zNPCGoalVillager.h"
#include "zNPCGoalRobo.h"
#include "zNPCGoalTiki.h"
#include "zNPCGoalDuplotron.h"
#include "zNPCGoalAmbient.h"
#include "zNPCGoalSubBoss.h"
#include "zNPCTypeDutchman.h"
#include "zNPCGoalBoss.h"
#include "zNPCTypeBossSB2.h"
#include "zNPCTypeBossPlankton.h"

void zNPCGoals_RegisterTypes(xFactory* fac)
{
    // clang-format off
    XGOFTypeInfo typelist[] =
    {
        NPC_GOAL_ID_IDLE, GOALCreate_Standard, GOALDestroy_Goal,
        NPC_GOAL_ID_WANDER, GOALCreate_Standard, GOALDestroy_Goal,
        NPC_GOAL_ID_PATROL, GOALCreate_Standard, GOALDestroy_Goal,
        NPC_GOAL_ID_FIDGET, GOALCreate_Standard, GOALDestroy_Goal,
        NPC_GOAL_ID_WAITING, GOALCreate_Standard, GOALDestroy_Goal,
        NPC_GOAL_ID_DEAD, GOALCreate_Standard, GOALDestroy_Goal,
        NPC_GOAL_ID_NOMANLAND, GOALCreate_Standard, GOALDestroy_Goal,
        NPC_GOAL_ID_LIMBO, GOALCreate_Standard, GOALDestroy_Goal,
        NPC_GOAL_ID_DEVANIMCYCLE, GOALCreate_Standard, GOALDestroy_Goal,
        NPC_GOAL_ID_DEVANIMSPIN, GOALCreate_Standard, GOALDestroy_Goal,
        NPC_GOAL_ID_DEVANIMHERO, GOALCreate_Standard, GOALDestroy_Goal,
        NPC_GOAL_ID_SCRIPT, GOALCreate_Script, GOALDestroy_Goal,
        NPC_GOAL_ID_SCRIPTANIM, GOALCreate_Script, GOALDestroy_Goal,
        NPC_GOAL_ID_SCRIPTATTACK, GOALCreate_Script, GOALDestroy_Goal,
        NPC_GOAL_ID_SCRIPTMOVE, GOALCreate_Script, GOALDestroy_Goal,
        NPC_GOAL_ID_SCRIPTTALK, GOALCreate_Script, GOALDestroy_Goal,
        NPC_GOAL_ID_SCRIPTFOLLOW, GOALCreate_Script, GOALDestroy_Goal,
        NPC_GOAL_ID_SCRIPTLEAD, GOALCreate_Script, GOALDestroy_Goal,
        NPC_GOAL_ID_SCRIPTWAIT, GOALCreate_Script, GOALDestroy_Goal,
        NPC_GOAL_ID_CHEER, GOALCreate_Villager, GOALDestroy_Goal,
        NPC_GOAL_ID_HURT, GOALCreate_Villager, GOALDestroy_Goal,
        NPC_GOAL_ID_PLAYERNEAR, GOALCreate_Villager, GOALDestroy_Goal,
        NPC_GOAL_ID_TALK, GOALCreate_Villager, GOALDestroy_Goal,
        NPC_GOAL_ID_CHATTER, GOALCreate_Villager, GOALDestroy_Goal,
        NPC_GOAL_ID_SPEAK, GOALCreate_Villager, GOALDestroy_Goal,
        NPC_GOAL_ID_BALLOON, GOALCreate_Villager, GOALDestroy_Goal,
        NPC_GOAL_ID_BOYRIDE, GOALCreate_Villager, GOALDestroy_Goal,
        NPC_GOAL_ID_BOYFALL, GOALCreate_Villager, GOALDestroy_Goal,
        NPC_GOAL_ID_BOYWEEP, GOALCreate_Villager, GOALDestroy_Goal,
        NPC_GOAL_ID_BOYSWIM, GOALCreate_Villager, GOALDestroy_Goal,
        NPC_GOAL_ID_NOTICE, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_TAUNT, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_EVADE, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_GOHOME, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_ALERT, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_ALERTFODDER, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_ALERTFODBOMB, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_ALERTFODBZZT, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_ALERTCHOMPER, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_ALERTHAMMER, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_ALERTTARTAR, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_ALERTGLOVE, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_ALERTMONSOON, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_ALERTSLEEPY, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_ALERTARF, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_ALERTPUPPY, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_ALERTCHUCK, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_ALERTTUBELET, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_ALERTSLICK, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_DOGLAUNCH, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_DOGBARK, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_DOGDASH, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_DOGPOUNCE, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_TELEPORT, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_HOKEYPOKEY, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_CHASE, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_ATTACKCQC, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_ATTACKFODDER, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_ATTACKCHOMPER, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_ATTACKHAMMER, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_ATTACKTARTAR, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_ATTACKMONSOON, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_ATTACKARF, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_ATTACKARFMELEE, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_ATTACKCHUCK, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_ATTACKSLICK, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_DEFLATE, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_TUBEPAL, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_TUBEDUCKLING, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_TUBEATTACK, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_TUBELASSO, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_TUBEBIRTH, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_TUBEBONKED, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_TUBEDYING, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_TUBEDEAD, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_LASSOBASE, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_LASSOGRAB, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_LASSOTHROW, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_EVILPAT, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_STUNNED, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_PATCARRY, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_PATTHROW, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_DAMAGE, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_KNOCK, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_R54, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_BASHED, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_R56, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_WOUND, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_AFTERLIFE, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_RESPAWN, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ID_TIKIIDLE, GOALCreate_Tiki, GOALDestroy_Goal,
        NPC_GOAL_ID_TIKIPATROL, GOALCreate_Tiki, GOALDestroy_Goal,
        NPC_GOAL_ID_TIKIHIDE, GOALCreate_Tiki, GOALDestroy_Goal,
        NPC_GOAL_ID_TIKICOUNT, GOALCreate_Tiki, GOALDestroy_Goal,
        NPC_GOAL_ID_TIKIDYING, GOALCreate_Tiki, GOALDestroy_Goal,
        NPC_GOAL_ID_TIKIDEAD, GOALCreate_Tiki, GOALDestroy_Goal,
        NPC_GOAL_ID_DUPLOLIVE, GOALCreate_Duplotron, GOALDestroy_Goal,
        NPC_GOAL_ID_DUPLODEAD, GOALCreate_Duplotron, GOALDestroy_Goal,
        NPC_GOAL_ID_JELLYATTACK, GOALCreate_Ambient, GOALDestroy_Goal,
        NPC_GOAL_ID_JELLYBUMPED, GOALCreate_Ambient, GOALDestroy_Goal,
        NPC_GOAL_ID_JELLYBIRTH, GOALCreate_Ambient, GOALDestroy_Goal,
        NPC_GOAL_ID_HERE, GOALCreate_SubBoss, GOALDestroy_Goal,
        NPC_GOAL_ID_KJIDLE, GOALCreate_SubBoss, GOALDestroy_Goal,
        NPC_GOAL_ID_KJBORED, GOALCreate_SubBoss, GOALDestroy_Goal,
        NPC_GOAL_ID_KJSPAWNKIDS, GOALCreate_SubBoss, GOALDestroy_Goal,
        NPC_GOAL_ID_KJTAUNT, GOALCreate_SubBoss, GOALDestroy_Goal,
        NPC_GOAL_ID_KJSHOCKGROUND, GOALCreate_SubBoss, GOALDestroy_Goal,
        NPC_GOAL_ID_KJDAMAGE, GOALCreate_SubBoss, GOALDestroy_Goal,
        NPC_GOAL_ID_KJDEATH, GOALCreate_SubBoss, GOALDestroy_Goal,
        NPC_GOAL_ID_PRAWNIDLE, GOALCreate_SubBoss, GOALDestroy_Goal,
        NPC_GOAL_ID_PRAWNBEAM, GOALCreate_SubBoss, GOALDestroy_Goal,
        NPC_GOAL_ID_PRAWNBOWL, GOALCreate_SubBoss, GOALDestroy_Goal,
        NPC_GOAL_ID_PRAWNDAMAGE, GOALCreate_SubBoss, GOALDestroy_Goal,
        NPC_GOAL_ID_PRAWNDEATH, GOALCreate_SubBoss, GOALDestroy_Goal,
        NPC_GOAL_ID_DUTCHMANNIL, zNPCGoalDutchmanNil::create, GOALDestroy_Goal,
        NPC_GOAL_ID_DUTCHMANINITIATE, zNPCGoalDutchmanInitiate::create, GOALDestroy_Goal,
        NPC_GOAL_ID_DUTCHMANIDLE, zNPCGoalDutchmanIdle::create, GOALDestroy_Goal,
        NPC_GOAL_ID_DUTCHMANDISAPPEAR, zNPCGoalDutchmanDisappear::create, GOALDestroy_Goal,
        NPC_GOAL_ID_DUTCHMANTELEPORT, zNPCGoalDutchmanTeleport::create, GOALDestroy_Goal,
        NPC_GOAL_ID_DUTCHMANREAPPEAR, zNPCGoalDutchmanReappear::create, GOALDestroy_Goal,
        NPC_GOAL_ID_DUTCHMANBEAM, zNPCGoalDutchmanBeam::create, GOALDestroy_Goal,
        NPC_GOAL_ID_DUTCHMANFLAME, zNPCGoalDutchmanFlame::create, GOALDestroy_Goal,
        NPC_GOAL_ID_DUTCHMANPOSTFLAME, zNPCGoalDutchmanPostFlame::create, GOALDestroy_Goal,
        NPC_GOAL_ID_DUTCHMANCAUGHT, zNPCGoalDutchmanCaught::create, GOALDestroy_Goal,
        NPC_GOAL_ID_DUTCHMANDAMAGE, zNPCGoalDutchmanDamage::create, GOALDestroy_Goal,
        NPC_GOAL_ID_DUTCHMANDEATH, zNPCGoalDutchmanDeath::create, GOALDestroy_Goal,
        NPC_GOAL_ID_EXIST, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_ID_BOSSSANDYIDLE, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_ID_BOSSSANDYTAUNT, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_ID_BOSSSANDYCHASE, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_ID_BOSSSANDYMELEE, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_ID_BOSSSANDYNOHEAD, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_ID_BOSSSANDYELBOWDROP, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_ID_BOSSSANDYLEAP, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_ID_BOSSSANDYSIT, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_ID_BOSSSANDYGETUP, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_ID_BOSSSANDYRUNTOROPE, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_ID_BOSSSANDYCLOTHESLINE, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_ID_BOSSPATIDLE, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_ID_BOSSPATTAUNT, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_ID_BOSSPATHIT, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_ID_BOSSPATSPIT, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_ID_BOSSPATRUN, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_ID_BOSSPATSMACK, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_ID_BOSSPATFREEZE, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_ID_BOSSPATSPAWN, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_ID_BOSSPATSPIN, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_ID_BOSSPATFUDGE, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_ID_BOSSSB1IDLE, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_ID_BOSSSB1TAUNT, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_ID_BOSSSB1STOMP, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_ID_BOSSSB1SMASH, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_ID_BOSSSB1DEFLATE, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_ID_BOSSSB2INTRO, zNPCGoalBossSB2Intro::create, GOALDestroy_Goal,
        NPC_GOAL_ID_BOSSSB2IDLE, zNPCGoalBossSB2Idle::create, GOALDestroy_Goal,
        NPC_GOAL_ID_BOSSSB2TAUNT, zNPCGoalBossSB2Taunt::create, GOALDestroy_Goal,
        NPC_GOAL_ID_BOSSSB2DIZZY, zNPCGoalBossSB2Dizzy::create, GOALDestroy_Goal,
        NPC_GOAL_ID_BOSSSB2HIT, zNPCGoalBossSB2Hit::create, GOALDestroy_Goal,
        NPC_GOAL_ID_BOSSSB2HUNT, zNPCGoalBossSB2Hunt::create, GOALDestroy_Goal,
        NPC_GOAL_ID_BOSSSB2SWIPE, zNPCGoalBossSB2Swipe::create, GOALDestroy_Goal,
        NPC_GOAL_ID_BOSSSB2CHOP, zNPCGoalBossSB2Chop::create, GOALDestroy_Goal,
        NPC_GOAL_ID_BOSSSB2KARATE, zNPCGoalBossSB2Karate::create, GOALDestroy_Goal,
        NPC_GOAL_ID_BOSSSB2DEATH, zNPCGoalBossSB2Death::create, GOALDestroy_Goal,
        NPC_GOAL_ID_BPLANKTONIDLE, zNPCGoalBPlanktonIdle::create, GOALDestroy_Goal,
        NPC_GOAL_ID_BPLANKTONATTACK, zNPCGoalBPlanktonAttack::create, GOALDestroy_Goal,
        NPC_GOAL_ID_BPLANKTONAMBUSH, zNPCGoalBPlanktonAmbush::create, GOALDestroy_Goal,
        NPC_GOAL_ID_BPLANKTONFLANK, zNPCGoalBPlanktonFlank::create, GOALDestroy_Goal,
        NPC_GOAL_ID_BPLANKTONEVADE, zNPCGoalBPlanktonEvade::create, GOALDestroy_Goal,
        NPC_GOAL_ID_BPLANKTONHUNT, zNPCGoalBPlanktonHunt::create, GOALDestroy_Goal,
        NPC_GOAL_ID_BPLANKTONTAUNT, zNPCGoalBPlanktonTaunt::create, GOALDestroy_Goal,
        NPC_GOAL_ID_BPLANKTONMOVE, zNPCGoalBPlanktonMove::create, GOALDestroy_Goal,
        NPC_GOAL_ID_BPLANKTONSTUN, zNPCGoalBPlanktonStun::create, GOALDestroy_Goal,
        NPC_GOAL_ID_BPLANKTONFALL, zNPCGoalBPlanktonFall::create, GOALDestroy_Goal,
        NPC_GOAL_ID_BPLANKTONDIZZY, zNPCGoalBPlanktonDizzy::create, GOALDestroy_Goal,
        NPC_GOAL_ID_BPLANKTONBEAM, zNPCGoalBPlanktonBeam::create, GOALDestroy_Goal,
        NPC_GOAL_ID_BPLANKTONWALL, zNPCGoalBPlanktonWall::create, GOALDestroy_Goal,
        NPC_GOAL_ID_BPLANKTONMISSLE, zNPCGoalBPlanktonMissle::create, GOALDestroy_Goal,
        NPC_GOAL_ID_BPLANKTONBOMB, zNPCGoalBPlanktonBomb::create, GOALDestroy_Goal,
        0
    };
    // clang-format on

    fac->RegItemType(typelist);
}