#ifndef ZNPCHAZARD_H
#define ZNPCHAZARD_H

#include <types.h>

enum en_npchaz
{
    NPC_HAZ_UNKNOWN,
    NPC_HAZ_EXPLODE,
    NPC_HAZ_EXPLODE_INNER,
    NPC_HAZ_FODBOMB,
    NPC_HAZ_CATTLEPROD,
    NPC_HAZ_TUBELETBLAST,
    NPC_HAZ_PUPPYNUKE,
    NPC_HAZ_DUPLOBOOM,
    NPC_HAZ_DUPLO_SHROOM,
    NPC_HAZ_PATRIOT,
    NPC_HAZ_TARTARPROJ,
    NPC_HAZ_TARTARSPILL,
    NPC_HAZ_TARTARSTINK,
    NPC_HAZ_CHUCKBOMB,
    NPC_HAZ_CHUCKBLAST,
    NPC_HAZ_CHUCKBLOOSH,
    NPC_HAZ_ARFBONE,
    NPC_HAZ_ARFBONEBLAST,
    NPC_HAZ_OILBUBBLE,
    NPC_HAZ_OILSLICK,
    NPC_HAZ_OILBURST,
    NPC_HAZ_OILGLOB,
    NPC_HAZ_MONCLOUD,
    NPC_HAZ_FUNFRAG,
    NPC_HAZ_THUNDER,
    NPC_HAZ_ROBOBITS,
    NPC_HAZ_VISSPLASH,
    NPC_HAZ_NOMORE,
    NPC_HAZ_FORCE = 0x7fffffff
};

void zNPCCommon_Hazards_RenderAll(int32 doOpaqueStuff);
void zNPCHazard_Shutdown();

#endif