INIT_O_FILES :=                                     \
    $(OBJ_DIR)/asm/init.o

EXTAB_O_FILES :=                                    \
    $(OBJ_DIR)/asm/extab.o

EXTABINDEX_O_FILES :=                               \
    $(OBJ_DIR)/asm/extabindex.o

CTORS_O_FILES :=                                    \
    $(OBJ_DIR)/asm/ctors.o

DTORS_O_FILES :=                                    \
    $(OBJ_DIR)/asm/dtors.o

RODATA_O_FILES :=                                   \
    $(OBJ_DIR)/asm/rodata.o

DATA_O_FILES :=                                     \
    $(OBJ_DIR)/asm/data.o

BSS_O_FILES :=                                      \
    $(OBJ_DIR)/asm/bss.o

SDATA_O_FILES :=                                    \
    $(OBJ_DIR)/asm/sdata.o

SBSS_O_FILES :=                                     \
    $(OBJ_DIR)/asm/sbss.o

SDATA2_O_FILES :=                                   \
    $(OBJ_DIR)/asm/sdata2.o

SBSS2_O_FILES :=                                    \
    $(OBJ_DIR)/asm/sbss2.o

NEW_FILES :=                                                          \
    $(OBJ_DIR)/asm/xAnim.o                                            \
    $(OBJ_DIR)/asm/xBase.o                                            \
    $(OBJ_DIR)/asm/xbinio.o                                           \
    $(OBJ_DIR)/asm/xBound.o                                           \
    $(OBJ_DIR)/asm/xCamera.o                                          \
    $(OBJ_DIR)/asm/xClimate.o                                         \
    $(OBJ_DIR)/asm/xCollide.o                                         \
    $(OBJ_DIR)/asm/xCollideFast.o                                     \
    $(OBJ_DIR)/asm/xColor.o                                           \
    $(OBJ_DIR)/asm/xCounter.o                                         \
    $(OBJ_DIR)/asm/xCutscene.o                                        \
    $(OBJ_DIR)/asm/xDebug.o                                           \
    $(OBJ_DIR)/asm/xEnt.o                                             \
    $(OBJ_DIR)/asm/xEntDrive.o                                        \
    $(OBJ_DIR)/asm/xEntMotion.o                                       \
    $(OBJ_DIR)/asm/xEnv.o                                             \
    $(OBJ_DIR)/asm/xEvent.o                                           \
    $(OBJ_DIR)/asm/xFFX.o                                             \
    $(OBJ_DIR)/asm/xFog.o                                             \
    $(OBJ_DIR)/asm/xFont.o                                            \
    $(OBJ_DIR)/asm/xFX.o                                              \
    $(OBJ_DIR)/asm/xGroup.o                                           \
    $(OBJ_DIR)/asm/xhipio.o                                           \
    $(OBJ_DIR)/asm/xHud.o                                             \
    $(OBJ_DIR)/asm/xHudFontMeter.o                                    \
    $(OBJ_DIR)/asm/xHudMeter.o                                        \
    $(OBJ_DIR)/asm/xHudModel.o                                        \
    $(OBJ_DIR)/asm/xHudUnitMeter.o                                    \
    $(OBJ_DIR)/asm/xIni.o                                             \
    $(OBJ_DIR)/asm/xMath.o                                            \
    $(OBJ_DIR)/asm/xMath2.o                                           \
    $(OBJ_DIR)/asm/xMath3.o                                           \
    $(OBJ_DIR)/asm/xMemMgr.o                                          \
    $(OBJ_DIR)/asm/xModel.o                                           \
    $(OBJ_DIR)/asm/xMorph.o                                           \
    $(OBJ_DIR)/asm/xMovePoint.o                                       \
    $(OBJ_DIR)/asm/xordarray.o                                        \
    $(OBJ_DIR)/asm/xPad.o                                             \
    $(OBJ_DIR)/asm/xPar.o                                             \
    $(OBJ_DIR)/asm/xParCmd.o                                          \
    $(OBJ_DIR)/asm/xParGroup.o                                        \
    $(OBJ_DIR)/asm/xParMgr.o                                          \
    $(OBJ_DIR)/asm/xPartition.o                                       \
    $(OBJ_DIR)/asm/xpkrsvc.o                                          \
    $(OBJ_DIR)/asm/xQuickCull.o                                       \
    $(OBJ_DIR)/asm/xsavegame.o                                        \
    $(OBJ_DIR)/asm/xScene.o                                           \
    $(OBJ_DIR)/asm/xScrFx.o                                           \
    $(OBJ_DIR)/asm/xserializer.o                                      \
    $(OBJ_DIR)/asm/xSFX.o                                             \
    $(OBJ_DIR)/asm/xShadow.o                                          \
    $(OBJ_DIR)/asm/xSnd.o                                             \
    $(OBJ_DIR)/asm/xSpline.o                                          \
    $(OBJ_DIR)/asm/xstransvc.o                                        \
    $(OBJ_DIR)/asm/xString.o                                          \
    $(OBJ_DIR)/asm/xSurface.o                                         \
    $(OBJ_DIR)/asm/xTimer.o                                           \
    $(OBJ_DIR)/asm/xTRC.o                                             \
    $(OBJ_DIR)/asm/xutil.o                                            \
    $(OBJ_DIR)/asm/xVec3.o                                            \
    $(OBJ_DIR)/asm/zActionLine.o                                      \
    $(OBJ_DIR)/asm/zAnimList.o                                        \
    $(OBJ_DIR)/asm/zAssetTypes.o                                      \
    $(OBJ_DIR)/asm/zCamera.o                                          \
    $(OBJ_DIR)/asm/zConditional.o                                     \
    $(OBJ_DIR)/asm/zCutsceneMgr.o                                     \
    $(OBJ_DIR)/asm/zDispatcher.o                                      \
    $(OBJ_DIR)/asm/zEGenerator.o                                      \
    $(OBJ_DIR)/asm/zEnt.o                                             \
    $(OBJ_DIR)/asm/zEntButton.o                                       \
    $(OBJ_DIR)/asm/zEntCruiseBubble.o                                 \
    $(OBJ_DIR)/asm/zEntDestructObj.o                                  \
    $(OBJ_DIR)/asm/zEntHangable.o                                     \
    $(OBJ_DIR)/asm/zEntPickup.o                                       \
    $(OBJ_DIR)/asm/zEntPlayer.o                                       \
    $(OBJ_DIR)/asm/zEntSimpleObj.o                                    \
    $(OBJ_DIR)/asm/zEntTrigger.o                                      \
    $(OBJ_DIR)/asm/zEnv.o                                             \
    $(OBJ_DIR)/asm/zEvent.o                                           \
    $(OBJ_DIR)/asm/zFeet.o                                            \
    $(OBJ_DIR)/asm/zFMV.o                                             \
    $(OBJ_DIR)/asm/zFX.o                                              \
    $(OBJ_DIR)/asm/zGame.o                                            \
    $(OBJ_DIR)/asm/zGameExtras.o                                      \
    $(OBJ_DIR)/asm/zGameState.o                                       \
    $(OBJ_DIR)/asm/zGust.o                                            \
    $(OBJ_DIR)/asm/zHud.o                                             \
    $(OBJ_DIR)/asm/zLasso.o                                           \
    $(OBJ_DIR)/asm/zLight.o                                           \
    $(OBJ_DIR)/asm/zLightEffect.o                                     \
    $(OBJ_DIR)/asm/zLightning.o                                       \
    $(OBJ_DIR)/asm/zLOD.o                                             \
    $(OBJ_DIR)/asm/zMain.o                                            \
    $(OBJ_DIR)/asm/zMenu.o                                            \
    $(OBJ_DIR)/asm/zMovePoint.o                                       \
    $(OBJ_DIR)/asm/zMusic.o                                           \
    $(OBJ_DIR)/asm/zParCmd.o                                          \
    $(OBJ_DIR)/asm/zParEmitter.o                                      \
    $(OBJ_DIR)/asm/zPendulum.o                                        \
    $(OBJ_DIR)/asm/zPickupTable.o                                     \
    $(OBJ_DIR)/asm/zPlatform.o                                        \
    $(OBJ_DIR)/asm/zPortal.o                                          \
    $(OBJ_DIR)/asm/zRenderState.o                                     \
    $(OBJ_DIR)/asm/zRumble.o                                          \
    $(OBJ_DIR)/asm/zSaveLoad.o                                        \
    $(OBJ_DIR)/asm/zScene.o                                           \
    $(OBJ_DIR)/asm/zScript.o                                          \
    $(OBJ_DIR)/asm/zSurface.o                                         \
    $(OBJ_DIR)/asm/zThrown.o                                          \
    $(OBJ_DIR)/asm/zUI.o                                              \
    $(OBJ_DIR)/asm/zUIFont.o                                          \
    $(OBJ_DIR)/asm/zVar.o                                             \
    $(OBJ_DIR)/asm/zVolume.o                                          \
    $(OBJ_DIR)/asm/iAnim.o                                            \
    $(OBJ_DIR)/asm/iAnimSKB.o                                         \
    $(OBJ_DIR)/asm/iCamera.o                                          \
    $(OBJ_DIR)/asm/iCollide.o                                         \
    $(OBJ_DIR)/asm/iCollideFast.o                                     \
    $(OBJ_DIR)/asm/iDraw.o                                            \
    $(OBJ_DIR)/asm/iEnv.o                                             \
    $(OBJ_DIR)/asm/iFile.o                                            \
    $(OBJ_DIR)/asm/iFMV.o                                             \
    $(OBJ_DIR)/asm/iFX.o                                              \
    $(OBJ_DIR)/asm/iLight.o                                           \
    $(OBJ_DIR)/asm/iMath.o                                            \
    $(OBJ_DIR)/asm/iMath3.o                                           \
    $(OBJ_DIR)/asm/iMemMgr.o                                          \
    $(OBJ_DIR)/asm/iMix.o                                             \
    $(OBJ_DIR)/asm/iModel.o                                           \
    $(OBJ_DIR)/asm/iMorph.o                                           \
    $(OBJ_DIR)/asm/iPad.o                                             \
    $(OBJ_DIR)/asm/iParMgr.o                                          \
    $(OBJ_DIR)/asm/isavegame.o                                        \
    $(OBJ_DIR)/asm/iScrFX.o                                           \
    $(OBJ_DIR)/asm/iSnd.o                                             \
    $(OBJ_DIR)/asm/iSystem.o                                          \
    $(OBJ_DIR)/asm/iTime.o                                            \
    $(OBJ_DIR)/asm/ngcrad3d.o                                         \
    $(OBJ_DIR)/asm/zNPCGoals.o                                        \
    $(OBJ_DIR)/asm/zNPCGoalCommon.o                                   \
    $(OBJ_DIR)/asm/zNPCGoalStd.o                                      \
    $(OBJ_DIR)/asm/zNPCGoalRobo.o                                     \
    $(OBJ_DIR)/asm/zNPCGoalTiki.o                                     \
    $(OBJ_DIR)/asm/zNPCMessenger.o                                    \
    $(OBJ_DIR)/asm/zNPCMgr.o                                          \
    $(OBJ_DIR)/asm/zNPCTypes.o                                        \
    $(OBJ_DIR)/asm/zNPCTypeCommon.o                                   \
    $(OBJ_DIR)/asm/zNPCTypeRobot.o                                    \
    $(OBJ_DIR)/asm/zNPCTypeVillager.o                                 \
    $(OBJ_DIR)/asm/zNPCTypeAmbient.o                                  \
    $(OBJ_DIR)/asm/zNPCTypeTiki.o                                     \
    $(OBJ_DIR)/asm/xBehaveMgr.o                                       \
    $(OBJ_DIR)/asm/xBehaviour.o                                       \
    $(OBJ_DIR)/asm/xBehaveGoalSimple.o                                \
    $(OBJ_DIR)/asm/xSkyDome.o                                         \
    $(OBJ_DIR)/asm/xRMemData.o                                        \
    $(OBJ_DIR)/asm/xFactory.o                                         \
    $(OBJ_DIR)/asm/xNPCBasic.o                                        \
    $(OBJ_DIR)/asm/zEntPlayerBungeeState.o                            \
    $(OBJ_DIR)/asm/zCollGeom.o                                        \
    $(OBJ_DIR)/asm/xParSys.o                                          \
    $(OBJ_DIR)/asm/xParEmitter.o                                      \
    $(OBJ_DIR)/asm/xVolume.o                                          \
    $(OBJ_DIR)/asm/xParEmitterType.o                                  \
    $(OBJ_DIR)/asm/xRenderState.o                                     \
    $(OBJ_DIR)/asm/zEntPlayerOOBState.o                               \
    $(OBJ_DIR)/asm/xClumpColl.o                                       \
    $(OBJ_DIR)/asm/xEntBoulder.o                                      \
    $(OBJ_DIR)/asm/xGrid.o                                            \
    $(OBJ_DIR)/asm/xJSP.o                                             \
    $(OBJ_DIR)/asm/xLightKit.o                                        \
    $(OBJ_DIR)/asm/zCamMarker.o                                       \
    $(OBJ_DIR)/asm/zGoo.o                                             \
    $(OBJ_DIR)/asm/zGrid.o                                            \
    $(OBJ_DIR)/asm/zNPCGoalScript.o                                   \
    $(OBJ_DIR)/asm/zNPCSndTable.o                                     \
    $(OBJ_DIR)/asm/zNPCSndLists.o                                     \
    $(OBJ_DIR)/asm/zNPCTypeDuplotron.o                                \
    $(OBJ_DIR)/asm/xModelBucket.o                                     \
    $(OBJ_DIR)/asm/zShrapnel.o                                        \
    $(OBJ_DIR)/asm/zNPCGoalDuplotron.o                                \
    $(OBJ_DIR)/asm/zNPCSpawner.o                                      \
    $(OBJ_DIR)/asm/zEntTeleportBox.o                                  \
    $(OBJ_DIR)/asm/zBusStop.o                                         \
    $(OBJ_DIR)/asm/zNPCSupport.o                                      \
    $(OBJ_DIR)/asm/zTalkBox.o                                         \
    $(OBJ_DIR)/asm/zTextBox.o                                         \
    $(OBJ_DIR)/asm/zTaskBox.o                                         \
    $(OBJ_DIR)/asm/iCutscene.o                                        \
    $(OBJ_DIR)/asm/zNPCTypeTest.o                                     \
    $(OBJ_DIR)/asm/zNPCTypeSubBoss.o                                  \
    $(OBJ_DIR)/asm/zNPCTypeBoss.o                                     \
    $(OBJ_DIR)/asm/zNPCGoalVillager.o                                 \
    $(OBJ_DIR)/asm/zNPCGoalSubBoss.o                                  \
    $(OBJ_DIR)/asm/xShadowSimple.o                                    \
    $(OBJ_DIR)/asm/xUpdateCull.o                                      \
    $(OBJ_DIR)/asm/zDiscoFloor.o                                      \
    $(OBJ_DIR)/asm/zNPCTypeBossSandy.o                                \
    $(OBJ_DIR)/asm/zNPCTypeKingJelly.o                                \
    $(OBJ_DIR)/asm/zNPCGoalBoss.o                                     \
    $(OBJ_DIR)/asm/zNPCTypePrawn.o                                    \
    $(OBJ_DIR)/asm/zNPCTypeBossSB1.o                                  \
    $(OBJ_DIR)/asm/zNPCTypeBossSB2.o                                  \
    $(OBJ_DIR)/asm/xJaw.o                                             \
    $(OBJ_DIR)/asm/zNPCTypeBossPatrick.o                              \
    $(OBJ_DIR)/asm/zNPCTypeBossPlankton.o                             \
    $(OBJ_DIR)/asm/zParPTank.o                                        \
    $(OBJ_DIR)/asm/zTaxi.o                                            \
    $(OBJ_DIR)/asm/zNPCTypeDutchman.o                                 \
    $(OBJ_DIR)/asm/zCameraFly.o                                       \
    $(OBJ_DIR)/asm/xCurveAsset.o                                      \
    $(OBJ_DIR)/asm/xDecal.o                                           \
    $(OBJ_DIR)/asm/xLaserBolt.o                                       \
    $(OBJ_DIR)/asm/zCameraTweak.o                                     \
    $(OBJ_DIR)/asm/xPtankPool.o                                       \
    $(OBJ_DIR)/asm/iTRC.o                                             \
    $(OBJ_DIR)/asm/zNPCSupplement.o                                   \
    $(OBJ_DIR)/asm/zNPCGlyph.o                                        \
    $(OBJ_DIR)/asm/zNPCHazard.o                                       \
    $(OBJ_DIR)/asm/zNPCGoalAmbient.o                                  \
    $(OBJ_DIR)/asm/zNPCFXCinematic.o                                  \
    $(OBJ_DIR)/asm/xHudText.o                                         \
    $(OBJ_DIR)/asm/zCombo.o                                           \
    $(OBJ_DIR)/asm/xCM.o                                              \
    $(OBJ_DIR)/asm/bink/binkngc.o                                     \
    $(OBJ_DIR)/asm/bink/ngcsnd.o                                      \
    $(OBJ_DIR)/asm/bink/binkread.o                                    \
    $(OBJ_DIR)/asm/bink/ngcfile.o                                     \
    $(OBJ_DIR)/asm/bink/yuv.o                                         \
    $(OBJ_DIR)/asm/bink/binkacd.o                                     \
    $(OBJ_DIR)/asm/bink/radcb.o                                       \
    $(OBJ_DIR)/asm/bink/expand.o                                      \
    $(OBJ_DIR)/asm/bink/popmal.o                                      \
    $(OBJ_DIR)/asm/bink/ngcrgb.o                                      \
    $(OBJ_DIR)/asm/bink/ngcyuy2.o                                     \
    $(OBJ_DIR)/asm/bink/varbits.o                                     \
    $(OBJ_DIR)/asm/bink/fft.o                                         \
    $(OBJ_DIR)/asm/bink/dct.o                                         \
    $(OBJ_DIR)/asm/bink/bitplane.o                                    \
    $(OBJ_DIR)/asm/ai.o                                               \
    $(OBJ_DIR)/asm/AmcExi2Stubs.o                                     \
    $(OBJ_DIR)/asm/ar.o                                               \
    $(OBJ_DIR)/asm/arq.o                                              \
    $(OBJ_DIR)/asm/AX.o                                               \
    $(OBJ_DIR)/asm/AXAlloc.o                                          \
    $(OBJ_DIR)/asm/AXAux.o                                            \
    $(OBJ_DIR)/asm/AXCL.o                                             \
    $(OBJ_DIR)/asm/AXOut.o                                            \
    $(OBJ_DIR)/asm/AXSPB.o                                            \
    $(OBJ_DIR)/asm/AXVPB.o                                            \
    $(OBJ_DIR)/asm/AXProf.o                                           \
    $(OBJ_DIR)/asm/AXComp.o                                           \
    $(OBJ_DIR)/asm/DSPCode.o                                          \
    $(OBJ_DIR)/asm/PPCArch.o                                          \
    $(OBJ_DIR)/asm/CARDBios.o                                         \
    $(OBJ_DIR)/asm/CARDUnlock.o                                       \
    $(OBJ_DIR)/asm/CARDRdwr.o                                         \
    $(OBJ_DIR)/asm/CARDBlock.o                                        \
    $(OBJ_DIR)/asm/CARDDir.o                                          \
    $(OBJ_DIR)/asm/CARDCheck.o                                        \
    $(OBJ_DIR)/asm/CARDMount.o                                        \
    $(OBJ_DIR)/asm/CARDFormat.o                                       \
    $(OBJ_DIR)/asm/CARDOpen.o                                         \
    $(OBJ_DIR)/asm/CARDCreate.o                                       \
    $(OBJ_DIR)/asm/CARDRead.o                                         \
    $(OBJ_DIR)/asm/CARDWrite.o                                        \
    $(OBJ_DIR)/asm/CARDDelete.o                                       \
    $(OBJ_DIR)/asm/CARDStat.o                                         \
    $(OBJ_DIR)/asm/CARDStatEx.o                                       \
    $(OBJ_DIR)/asm/CARDNet.o                                          \
    $(OBJ_DIR)/asm/db.o                                               \
    $(OBJ_DIR)/asm/dsp.o                                              \
    $(OBJ_DIR)/asm/dsp_debug.o                                        \
    $(OBJ_DIR)/asm/dsp_task.o                                         \
    $(OBJ_DIR)/asm/dvdlow.o                                           \
    $(OBJ_DIR)/asm/dvdfs.o                                            \
    $(OBJ_DIR)/asm/dvd.o                                              \
    $(OBJ_DIR)/asm/dvdqueue.o                                         \
    $(OBJ_DIR)/asm/dvderror.o                                         \
    $(OBJ_DIR)/asm/dvdidutils.o                                       \
    $(OBJ_DIR)/asm/dvdFatal.o                                         \
    $(OBJ_DIR)/asm/fstload.o                                          \
    $(OBJ_DIR)/asm/EXIBios.o                                          \
    $(OBJ_DIR)/asm/EXIUart.o                                          \
    $(OBJ_DIR)/asm/GXInit.o                                           \
    $(OBJ_DIR)/asm/GXFifo.o                                           \
    $(OBJ_DIR)/asm/GXAttr.o                                           \
    $(OBJ_DIR)/asm/GXMisc.o                                           \
    $(OBJ_DIR)/asm/GXGeometry.o                                       \
    $(OBJ_DIR)/asm/GXFrameBuf.o                                       \
    $(OBJ_DIR)/asm/GXLight.o                                          \
    $(OBJ_DIR)/asm/GXTexture.o                                        \
    $(OBJ_DIR)/asm/GXBump.o                                           \
    $(OBJ_DIR)/asm/GXTev.o                                            \
    $(OBJ_DIR)/asm/GXPixel.o                                          \
    $(OBJ_DIR)/asm/GXDisplayList.o                                    \
    $(OBJ_DIR)/asm/GXTransform.o                                      \
    $(OBJ_DIR)/asm/GXPerf.o                                           \
    $(OBJ_DIR)/asm/mtx.o                                              \
    $(OBJ_DIR)/asm/mtx44.o                                            \
    $(OBJ_DIR)/asm/odenotstub.o                                       \
    $(OBJ_DIR)/asm/OS.o                                               \
    $(OBJ_DIR)/asm/OSAlarm.o                                          \
    $(OBJ_DIR)/asm/OSAlloc.o                                          \
    $(OBJ_DIR)/asm/OSArena.o                                          \
    $(OBJ_DIR)/asm/OSAudioSystem.o                                    \
    $(OBJ_DIR)/asm/OSCache.o                                          \
    $(OBJ_DIR)/asm/OSContext.o                                        \
    $(OBJ_DIR)/asm/OSError.o                                          \
    $(OBJ_DIR)/asm/OSFont.o                                           \
    $(OBJ_DIR)/asm/OSInterrupt.o                                      \
    $(OBJ_DIR)/asm/OSLink.o                                           \
    $(OBJ_DIR)/asm/OSMemory.o                                         \
    $(OBJ_DIR)/asm/OSMutex.o                                          \
    $(OBJ_DIR)/asm/OSReboot.o                                         \
    $(OBJ_DIR)/asm/OSReset.o                                          \
    $(OBJ_DIR)/asm/OSResetSW.o                                        \
    $(OBJ_DIR)/asm/OSRtc.o                                            \
    $(OBJ_DIR)/asm/OSSync.o                                           \
    $(OBJ_DIR)/asm/OSThread.o                                         \
    $(OBJ_DIR)/asm/OSTime.o                                           \
    $(OBJ_DIR)/asm/__start.o                                          \
    $(OBJ_DIR)/asm/__ppc_eabi_init.o                                  \
    $(OBJ_DIR)/asm/Padclamp.o                                         \
    $(OBJ_DIR)/asm/Pad.o                                              \
    $(OBJ_DIR)/asm/SIBios.o                                           \
    $(OBJ_DIR)/asm/SISamplingRate.o                                   \
    $(OBJ_DIR)/asm/vi.o                                               \
    $(OBJ_DIR)/asm/abort_exit.o                                       \
    $(OBJ_DIR)/asm/alloc.o                                            \
    $(OBJ_DIR)/asm/ansi_files.o                                       \
    $(OBJ_DIR)/asm/ansi_fp.o                                          \
    $(OBJ_DIR)/asm/arith.o                                            \
    $(OBJ_DIR)/asm/buffer_io.o                                        \
    $(OBJ_DIR)/asm/char_io.o                                          \
    $(OBJ_DIR)/asm/critical_regions.gamecube.o                        \
    $(OBJ_DIR)/asm/ctype.o                                            \
    $(OBJ_DIR)/asm/direct_io.o                                        \
    $(OBJ_DIR)/asm/errno.o                                            \
    $(OBJ_DIR)/asm/file_io.o                                          \
    $(OBJ_DIR)/asm/FILE_POS.C.o                                       \
    $(OBJ_DIR)/asm/locale.o                                           \
    $(OBJ_DIR)/asm/mbstring.o                                         \
    $(OBJ_DIR)/asm/mem.o                                              \
    $(OBJ_DIR)/asm/mem_funcs.o                                        \
    $(OBJ_DIR)/asm/misc_io.o                                          \
    $(OBJ_DIR)/asm/printf.o                                           \
    $(OBJ_DIR)/asm/qsort.o                                            \
    $(OBJ_DIR)/asm/rand.o                                             \
    $(OBJ_DIR)/asm/scanf.o                                            \
    $(OBJ_DIR)/asm/signal.o                                           \
    $(OBJ_DIR)/asm/string.o                                           \
    $(OBJ_DIR)/asm/strtold.o                                          \
    $(OBJ_DIR)/asm/strtoul.o                                          \
    $(OBJ_DIR)/asm/uart_console_io.o                                  \
    $(OBJ_DIR)/asm/float.o                                            \
    $(OBJ_DIR)/asm/wchar_io.o                                         \
    $(OBJ_DIR)/asm/e_acos.o                                           \
    $(OBJ_DIR)/asm/e_asin.o                                           \
    $(OBJ_DIR)/asm/e_atan2.o                                          \
    $(OBJ_DIR)/asm/e_exp.o                                            \
    $(OBJ_DIR)/asm/e_fmod.o                                           \
    $(OBJ_DIR)/asm/e_log.o                                            \
    $(OBJ_DIR)/asm/e_pow.o                                            \
    $(OBJ_DIR)/asm/e_rem_pio2.o                                       \
    $(OBJ_DIR)/asm/k_cos.o                                            \
    $(OBJ_DIR)/asm/k_rem_pio2.o                                       \
    $(OBJ_DIR)/asm/k_sin.o                                            \
    $(OBJ_DIR)/asm/k_tan.o                                            \
    $(OBJ_DIR)/asm/s_atan.o                                           \
    $(OBJ_DIR)/asm/s_ceil.o                                           \
    $(OBJ_DIR)/asm/s_copysign.o                                       \
    $(OBJ_DIR)/asm/s_cos.o                                            \
    $(OBJ_DIR)/asm/s_floor.o                                          \
    $(OBJ_DIR)/asm/s_frexp.o                                          \
    $(OBJ_DIR)/asm/s_ldexp.o                                          \
    $(OBJ_DIR)/asm/s_modf.o                                           \
    $(OBJ_DIR)/asm/s_sin.o                                            \
    $(OBJ_DIR)/asm/s_tan.o                                            \
    $(OBJ_DIR)/asm/w_acos.o                                           \
    $(OBJ_DIR)/asm/w_asin.o                                           \
    $(OBJ_DIR)/asm/w_atan2.o                                          \
    $(OBJ_DIR)/asm/w_exp.o                                            \
    $(OBJ_DIR)/asm/w_fmod.o                                           \
    $(OBJ_DIR)/asm/w_log.o                                            \
    $(OBJ_DIR)/asm/w_pow.o                                            \
    $(OBJ_DIR)/asm/math_ppc.o                                         \
    $(OBJ_DIR)/asm/extras.o                                           \
    $(OBJ_DIR)/asm/__mem.o                                            \
    $(OBJ_DIR)/asm/__va_arg.o                                         \
    $(OBJ_DIR)/asm/global_destructor_chain.o                          \
    $(OBJ_DIR)/asm/CPlusLibPPC.o                                      \
    $(OBJ_DIR)/asm/New.o                                              \
    $(OBJ_DIR)/asm/NMWException.o                                     \
    $(OBJ_DIR)/asm/runtime.o                                          \
    $(OBJ_DIR)/asm/__init_cpp_exceptions.o                            \
    $(OBJ_DIR)/asm/Gecko_ExceptionPPC.o                               \
    $(OBJ_DIR)/asm/GCN_mem_alloc.o                                    \
    $(OBJ_DIR)/asm/mainloop.o                                         \
    $(OBJ_DIR)/asm/nubevent.o                                         \
    $(OBJ_DIR)/asm/nubinit.o                                          \
    $(OBJ_DIR)/asm/msg.o                                              \
    $(OBJ_DIR)/asm/msgbuf.o                                           \
    $(OBJ_DIR)/asm/serpoll.o                                          \
    $(OBJ_DIR)/asm/usr_put.o                                          \
    $(OBJ_DIR)/asm/dispatch.o                                         \
    $(OBJ_DIR)/asm/msghndlr.o                                         \
    $(OBJ_DIR)/asm/support.o                                          \
    $(OBJ_DIR)/asm/mutex_TRK.o                                        \
    $(OBJ_DIR)/asm/notify.o                                           \
    $(OBJ_DIR)/asm/flush_cache.o                                      \
    $(OBJ_DIR)/asm/mem_TRK.o                                          \
    $(OBJ_DIR)/asm/__exception.o                                      \
    $(OBJ_DIR)/asm/targimpl.o                                         \
    $(OBJ_DIR)/asm/targsupp.o                                         \
    $(OBJ_DIR)/asm/dolphin_trk.o                                      \
    $(OBJ_DIR)/asm/mpc_7xx_603e.o                                     \
    $(OBJ_DIR)/asm/main_TRK.o                                         \
    $(OBJ_DIR)/asm/dolphin_trk_glue.o                                 \
    $(OBJ_DIR)/asm/targcont.o                                         \
    $(OBJ_DIR)/asm/target_options.o                                   \
    $(OBJ_DIR)/asm/mslsupp.o                                          \
    $(OBJ_DIR)/asm/DebuggerDriver.o                                   \
    $(OBJ_DIR)/asm/ctgeom.o                                           \
    $(OBJ_DIR)/asm/ctworld.o                                          \
    $(OBJ_DIR)/asm/ctbsp.o                                            \
    $(OBJ_DIR)/asm/rpcollis.o                                         \
    $(OBJ_DIR)/asm/stdkey.o                                           \
    $(OBJ_DIR)/asm/rphanim.o                                          \
    $(OBJ_DIR)/asm/effectPipesGcn.o                                   \
    $(OBJ_DIR)/asm/multiTexGcnData.o                                  \
    $(OBJ_DIR)/asm/multiTexGcnPipe.o                                  \
    $(OBJ_DIR)/asm/multiTexGcn.o                                      \
    $(OBJ_DIR)/asm/multiTex.o                                         \
    $(OBJ_DIR)/asm/multiTexEffect.o                                   \
    $(OBJ_DIR)/asm/rpmatfx.o                                          \
    $(OBJ_DIR)/asm/rpptank.o                                          \
    $(OBJ_DIR)/asm/ptankgcn.o                                         \
    $(OBJ_DIR)/asm/ptankgcncallbacks.o                                \
    $(OBJ_DIR)/asm/ptankgcnrender.o                                   \
    $(OBJ_DIR)/asm/ptankgcntransforms.o                               \
    $(OBJ_DIR)/asm/ptankgcn_nc_ppm.o                                  \
    $(OBJ_DIR)/asm/ptankgcn_cc_ppm.o                                  \
    $(OBJ_DIR)/asm/ptankgcn_nc_cs_nr.o                                \
    $(OBJ_DIR)/asm/ptankgcn_cc_cs_nr.o                                \
    $(OBJ_DIR)/asm/ptankgcn_nc_pps_nr.o                               \
    $(OBJ_DIR)/asm/ptankgcn_cc_pps_nr.o                               \
    $(OBJ_DIR)/asm/ptankgcn_nc_cs_ppr.o                               \
    $(OBJ_DIR)/asm/ptankgcn_cc_cs_ppr.o                               \
    $(OBJ_DIR)/asm/ptankgcn_nc_pps_ppr.o                              \
    $(OBJ_DIR)/asm/ptankgcn_cc_pps_ppr.o                              \
    $(OBJ_DIR)/asm/bsplit.o                                           \
    $(OBJ_DIR)/asm/rpskin.o                                           \
    $(OBJ_DIR)/asm/skingcn.o                                          \
    $(OBJ_DIR)/asm/skinstream.o                                       \
    $(OBJ_DIR)/asm/instanceskin.o                                     \
    $(OBJ_DIR)/asm/skinmatrixblend.o                                  \
    $(OBJ_DIR)/asm/skingcnasm.o                                       \
    $(OBJ_DIR)/asm/skingcng.o                                         \
    $(OBJ_DIR)/asm/rpusrdat.o                                         \
    $(OBJ_DIR)/asm/babinwor.o                                         \
    $(OBJ_DIR)/asm/baclump.o                                          \
    $(OBJ_DIR)/asm/bageomet.o                                         \
    $(OBJ_DIR)/asm/balight.o                                          \
    $(OBJ_DIR)/asm/bamateri.o                                         \
    $(OBJ_DIR)/asm/bamatlst.o                                         \
    $(OBJ_DIR)/asm/bamesh.o                                           \
    $(OBJ_DIR)/asm/bameshop.o                                         \
    $(OBJ_DIR)/asm/basector.o                                         \
    $(OBJ_DIR)/asm/baworld.o                                          \
    $(OBJ_DIR)/asm/baworobj.o                                         \
    $(OBJ_DIR)/asm/bapipew.o                                          \
    $(OBJ_DIR)/asm/gcpipe.o                                           \
    $(OBJ_DIR)/asm/vtxfmt.o                                           \
    $(OBJ_DIR)/asm/wrldpipe.o                                         \
    $(OBJ_DIR)/asm/nodeGameCubeAtomicAllInOne.o                       \
    $(OBJ_DIR)/asm/nodeGameCubeWorldSectorAllInOne.o                  \
    $(OBJ_DIR)/asm/gclights.o                                         \
    $(OBJ_DIR)/asm/gcmorph.o                                          \
    $(OBJ_DIR)/asm/native.o                                           \
    $(OBJ_DIR)/asm/setup.o                                            \
    $(OBJ_DIR)/asm/geomcond.o                                         \
    $(OBJ_DIR)/asm/geominst.o                                         \
    $(OBJ_DIR)/asm/ibuffer.o                                          \
    $(OBJ_DIR)/asm/instancegeom.o                                     \
    $(OBJ_DIR)/asm/instanceworld.o                                    \
    $(OBJ_DIR)/asm/itools.o                                           \
    $(OBJ_DIR)/asm/vbuffer.o                                          \
    $(OBJ_DIR)/asm/vtools.o                                           \
    $(OBJ_DIR)/asm/vtxdesc.o                                          \
    $(OBJ_DIR)/asm/rtanim.o                                           \
    $(OBJ_DIR)/asm/rtintsec.o                                         \
    $(OBJ_DIR)/asm/rtslerp.o                                          \
    $(OBJ_DIR)/asm/babinary.o                                         \
    $(OBJ_DIR)/asm/bacolor.o                                          \
    $(OBJ_DIR)/asm/baerr.o                                            \
    $(OBJ_DIR)/asm/bafsys.o                                           \
    $(OBJ_DIR)/asm/baimmedi.o                                         \
    $(OBJ_DIR)/asm/bamatrix.o                                         \
    $(OBJ_DIR)/asm/bamemory.o                                         \
    $(OBJ_DIR)/asm/baresour.o                                         \
    $(OBJ_DIR)/asm/bastream.o                                         \
    $(OBJ_DIR)/asm/batkbin.o                                          \
    $(OBJ_DIR)/asm/batkreg.o                                          \
    $(OBJ_DIR)/asm/bavector.o                                         \
    $(OBJ_DIR)/asm/resmem.o                                           \
    $(OBJ_DIR)/asm/rwstring.o                                         \
    $(OBJ_DIR)/asm/osintf.o                                           \
    $(OBJ_DIR)/asm/babbox.o                                           \
    $(OBJ_DIR)/asm/babincam.o                                         \
    $(OBJ_DIR)/asm/babinfrm.o                                         \
    $(OBJ_DIR)/asm/babintex.o                                         \
    $(OBJ_DIR)/asm/bacamera.o                                         \
    $(OBJ_DIR)/asm/badevice.o                                         \
    $(OBJ_DIR)/asm/baframe.o                                          \
    $(OBJ_DIR)/asm/baimage.o                                          \
    $(OBJ_DIR)/asm/baimras.o                                          \
    $(OBJ_DIR)/asm/baraster.o                                         \
    $(OBJ_DIR)/asm/baresamp.o                                         \
    $(OBJ_DIR)/asm/basync.o                                           \
    $(OBJ_DIR)/asm/batextur.o                                         \
    $(OBJ_DIR)/asm/batypehf.o                                         \
    $(OBJ_DIR)/asm/palquant.o                                         \
    $(OBJ_DIR)/asm/dl2drend.o                                         \
    $(OBJ_DIR)/asm/dlconvrt.o                                         \
    $(OBJ_DIR)/asm/dldevice.o                                         \
    $(OBJ_DIR)/asm/dlraster.o                                         \
    $(OBJ_DIR)/asm/dlrendst.o                                         \
    $(OBJ_DIR)/asm/dlsprite.o                                         \
    $(OBJ_DIR)/asm/dltexdic.o                                         \
    $(OBJ_DIR)/asm/dltextur.o                                         \
    $(OBJ_DIR)/asm/dltoken.o                                          \
    $(OBJ_DIR)/asm/baim3d.o                                           \
    $(OBJ_DIR)/asm/bapipe.o                                           \
    $(OBJ_DIR)/asm/p2altmdl.o                                         \
    $(OBJ_DIR)/asm/p2core.o                                           \
    $(OBJ_DIR)/asm/p2define.o                                         \
    $(OBJ_DIR)/asm/p2dep.o                                            \
    $(OBJ_DIR)/asm/p2heap.o                                           \
    $(OBJ_DIR)/asm/p2renderstate.o                                    \
    $(OBJ_DIR)/asm/p2resort.o                                         \
    $(OBJ_DIR)/asm/im3dpipe.o                                         \
    $(OBJ_DIR)/asm/nodeDolphinSubmitNoLight.o                         \
