#include "zNPCGoals.h"

#include "zNPCGoalStd.h"
#include "zNPCGoalScript.h"
#include "zNPCGoalVillager.h"
#include "zNPCGoalRobo.h"
#include "zNPCGoalTiki.h"
#include "zNPCGoalDuplotron.h"
#include "zNPCGoalAmbient.h"
#include "zNPCGoalSubBoss.h"
#include "zNPCTypeDutchman.h"
#include "zNPCGoalBoss.h"
#include "zNPCTypeBossSB2.h"
#include "zNPCTypeBossPlankton.h"

void zNPCGoals_RegisterTypes(xFactory* fac)
{
    // clang-format off
    XGOFTypeInfo typelist[] =
    {
        NPC_GOAL_IDLE, GOALCreate_Standard, GOALDestroy_Goal,
        NPC_GOAL_WANDER, GOALCreate_Standard, GOALDestroy_Goal,
        NPC_GOAL_PATROL, GOALCreate_Standard, GOALDestroy_Goal,
        NPC_GOAL_FIDGET, GOALCreate_Standard, GOALDestroy_Goal,
        NPC_GOAL_WAITING, GOALCreate_Standard, GOALDestroy_Goal,
        NPC_GOAL_DEAD, GOALCreate_Standard, GOALDestroy_Goal,
        NPC_GOAL_NOMANLAND, GOALCreate_Standard, GOALDestroy_Goal,
        NPC_GOAL_LIMBO, GOALCreate_Standard, GOALDestroy_Goal,
        NPC_GOAL_DEVANIMCYCLE, GOALCreate_Standard, GOALDestroy_Goal,
        NPC_GOAL_DEVANIMSPIN, GOALCreate_Standard, GOALDestroy_Goal,
        NPC_GOAL_DEVANIMHERO, GOALCreate_Standard, GOALDestroy_Goal,
        NPC_GOAL_SCRIPT, GOALCreate_Script, GOALDestroy_Goal,
        NPC_GOAL_SCRIPTANIM, GOALCreate_Script, GOALDestroy_Goal,
        NPC_GOAL_SCRIPTATTACK, GOALCreate_Script, GOALDestroy_Goal,
        NPC_GOAL_SCRIPTMOVE, GOALCreate_Script, GOALDestroy_Goal,
        NPC_GOAL_SCRIPTTALK, GOALCreate_Script, GOALDestroy_Goal,
        NPC_GOAL_SCRIPTFOLLOW, GOALCreate_Script, GOALDestroy_Goal,
        NPC_GOAL_SCRIPTLEAD, GOALCreate_Script, GOALDestroy_Goal,
        NPC_GOAL_SCRIPTWAIT, GOALCreate_Script, GOALDestroy_Goal,
        NPC_GOAL_CHEER, GOALCreate_Villager, GOALDestroy_Goal,
        NPC_GOAL_HURT, GOALCreate_Villager, GOALDestroy_Goal,
        NPC_GOAL_PLAYERNEAR, GOALCreate_Villager, GOALDestroy_Goal,
        NPC_GOAL_TALK, GOALCreate_Villager, GOALDestroy_Goal,
        NPC_GOAL_CHATTER, GOALCreate_Villager, GOALDestroy_Goal,
        NPC_GOAL_SPEAK, GOALCreate_Villager, GOALDestroy_Goal,
        NPC_GOAL_BALLOON, GOALCreate_Villager, GOALDestroy_Goal,
        NPC_GOAL_BOYRIDE, GOALCreate_Villager, GOALDestroy_Goal,
        NPC_GOAL_BOYFALL, GOALCreate_Villager, GOALDestroy_Goal,
        NPC_GOAL_BOYWEEP, GOALCreate_Villager, GOALDestroy_Goal,
        NPC_GOAL_BOYSWIM, GOALCreate_Villager, GOALDestroy_Goal,
        NPC_GOAL_NOTICE, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_TAUNT, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_EVADE, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_GOHOME, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ALERT, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ALERTFODDER, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ALERTFODBOMB, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ALERTFODBZZT, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ALERTCHOMPER, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ALERTHAMMER, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ALERTTARTAR, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ALERTGLOVE, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ALERTMONSOON, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ALERTSLEEPY, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ALERTARF, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ALERTPUPPY, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ALERTCHUCK, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ALERTTUBELET, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ALERTSLICK, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_DOGLAUNCH, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_DOGBARK, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_DOGDASH, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_DOGPOUNCE, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_TELEPORT, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_HOKEYPOKEY, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_CHASE, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ATTACKCQC, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ATTACKFODDER, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ATTACKCHOMPER, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ATTACKHAMMER, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ATTACKTARTAR, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ATTACKMONSOON, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ATTACKARF, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ATTACKARFMELEE, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ATTACKCHUCK, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_ATTACKSLICK, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_DEFLATE, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_TUBEPAL, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_TUBEDUCKLING, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_TUBEATTACK, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_TUBELASSO, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_TUBEBIRTH, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_TUBEBONKED, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_TUBEDYING, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_TUBEDEAD, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_LASSOBASE, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_LASSOGRAB, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_LASSOTHROW, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_EVILPAT, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_STUNNED, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_PATCARRY, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_PATTHROW, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_DAMAGE, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_KNOCK, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_R54, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_BASHED, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_R56, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_WOUND, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_AFTERLIFE, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_RESPAWN, GOALCreate_Robotic, GOALDestroy_Goal,
        NPC_GOAL_TIKIIDLE, GOALCreate_Tiki, GOALDestroy_Goal,
        NPC_GOAL_TIKIPATROL, GOALCreate_Tiki, GOALDestroy_Goal,
        NPC_GOAL_TIKIHIDE, GOALCreate_Tiki, GOALDestroy_Goal,
        NPC_GOAL_TIKICOUNT, GOALCreate_Tiki, GOALDestroy_Goal,
        NPC_GOAL_TIKIDYING, GOALCreate_Tiki, GOALDestroy_Goal,
        NPC_GOAL_TIKIDEAD, GOALCreate_Tiki, GOALDestroy_Goal,
        NPC_GOAL_DUPLOLIVE, GOALCreate_Duplotron, GOALDestroy_Goal,
        NPC_GOAL_DUPLODEAD, GOALCreate_Duplotron, GOALDestroy_Goal,
        NPC_GOAL_JELLYATTACK, GOALCreate_Ambient, GOALDestroy_Goal,
        NPC_GOAL_JELLYBUMPED, GOALCreate_Ambient, GOALDestroy_Goal,
        NPC_GOAL_JELLYBIRTH, GOALCreate_Ambient, GOALDestroy_Goal,
        NPC_GOAL_HERE, GOALCreate_SubBoss, GOALDestroy_Goal,
        NPC_GOAL_KJIDLE, GOALCreate_SubBoss, GOALDestroy_Goal,
        NPC_GOAL_KJBORED, GOALCreate_SubBoss, GOALDestroy_Goal,
        NPC_GOAL_KJSPAWNKIDS, GOALCreate_SubBoss, GOALDestroy_Goal,
        NPC_GOAL_KJTAUNT, GOALCreate_SubBoss, GOALDestroy_Goal,
        NPC_GOAL_KJSHOCKGROUND, GOALCreate_SubBoss, GOALDestroy_Goal,
        NPC_GOAL_KJDAMAGE, GOALCreate_SubBoss, GOALDestroy_Goal,
        NPC_GOAL_KJDEATH, GOALCreate_SubBoss, GOALDestroy_Goal,
        NPC_GOAL_PRAWNIDLE, GOALCreate_SubBoss, GOALDestroy_Goal,
        NPC_GOAL_PRAWNBEAM, GOALCreate_SubBoss, GOALDestroy_Goal,
        NPC_GOAL_PRAWNBOWL, GOALCreate_SubBoss, GOALDestroy_Goal,
        NPC_GOAL_PRAWNDAMAGE, GOALCreate_SubBoss, GOALDestroy_Goal,
        NPC_GOAL_PRAWNDEATH, GOALCreate_SubBoss, GOALDestroy_Goal,
        NPC_GOAL_DUTCHMANNIL, zNPCGoalDutchmanNil::create, GOALDestroy_Goal,
        NPC_GOAL_DUTCHMANINITIATE, zNPCGoalDutchmanInitiate::create, GOALDestroy_Goal,
        NPC_GOAL_DUTCHMANIDLE, zNPCGoalDutchmanIdle::create, GOALDestroy_Goal,
        NPC_GOAL_DUTCHMANDISAPPEAR, zNPCGoalDutchmanDisappear::create, GOALDestroy_Goal,
        NPC_GOAL_DUTCHMANTELEPORT, zNPCGoalDutchmanTeleport::create, GOALDestroy_Goal,
        NPC_GOAL_DUTCHMANREAPPEAR, zNPCGoalDutchmanReappear::create, GOALDestroy_Goal,
        NPC_GOAL_DUTCHMANBEAM, zNPCGoalDutchmanBeam::create, GOALDestroy_Goal,
        NPC_GOAL_DUTCHMANFLAME, zNPCGoalDutchmanFlame::create, GOALDestroy_Goal,
        NPC_GOAL_DUTCHMANPOSTFLAME, zNPCGoalDutchmanPostFlame::create, GOALDestroy_Goal,
        NPC_GOAL_DUTCHMANCAUGHT, zNPCGoalDutchmanCaught::create, GOALDestroy_Goal,
        NPC_GOAL_DUTCHMANDAMAGE, zNPCGoalDutchmanDamage::create, GOALDestroy_Goal,
        NPC_GOAL_DUTCHMANDEATH, zNPCGoalDutchmanDeath::create, GOALDestroy_Goal,
        NPC_GOAL_EXIST, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_BOSSSANDYIDLE, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_BOSSSANDYTAUNT, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_BOSSSANDYCHASE, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_BOSSSANDYMELEE, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_BOSSSANDYNOHEAD, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_BOSSSANDYELBOWDROP, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_BOSSSANDYLEAP, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_BOSSSANDYSIT, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_BOSSSANDYGETUP, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_BOSSSANDYRUNTOROPE, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_BOSSSANDYCLOTHESLINE, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_BOSSPATIDLE, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_BOSSPATTAUNT, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_BOSSPATHIT, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_BOSSPATSPIT, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_BOSSPATRUN, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_BOSSPATSMACK, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_BOSSPATFREEZE, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_BOSSPATSPAWN, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_BOSSPATSPIN, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_BOSSPATFUDGE, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_BOSSSB1IDLE, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_BOSSSB1TAUNT, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_BOSSSB1STOMP, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_BOSSSB1SMASH, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_BOSSSB1DEFLATE, GOALCreate_Boss, GOALDestroy_Goal,
        NPC_GOAL_BOSSSB2INTRO, zNPCGoalBossSB2Intro::create, GOALDestroy_Goal,
        NPC_GOAL_BOSSSB2IDLE, zNPCGoalBossSB2Idle::create, GOALDestroy_Goal,
        NPC_GOAL_BOSSSB2TAUNT, zNPCGoalBossSB2Taunt::create, GOALDestroy_Goal,
        NPC_GOAL_BOSSSB2DIZZY, zNPCGoalBossSB2Dizzy::create, GOALDestroy_Goal,
        NPC_GOAL_BOSSSB2HIT, zNPCGoalBossSB2Hit::create, GOALDestroy_Goal,
        NPC_GOAL_BOSSSB2HUNT, zNPCGoalBossSB2Hunt::create, GOALDestroy_Goal,
        NPC_GOAL_BOSSSB2SWIPE, zNPCGoalBossSB2Swipe::create, GOALDestroy_Goal,
        NPC_GOAL_BOSSSB2CHOP, zNPCGoalBossSB2Chop::create, GOALDestroy_Goal,
        NPC_GOAL_BOSSSB2KARATE, zNPCGoalBossSB2Karate::create, GOALDestroy_Goal,
        NPC_GOAL_BOSSSB2DEATH, zNPCGoalBossSB2Death::create, GOALDestroy_Goal,
        NPC_GOAL_BPLANKTONIDLE, zNPCGoalBPlanktonIdle::create, GOALDestroy_Goal,
        NPC_GOAL_BPLANKTONATTACK, zNPCGoalBPlanktonAttack::create, GOALDestroy_Goal,
        NPC_GOAL_BPLANKTONAMBUSH, zNPCGoalBPlanktonAmbush::create, GOALDestroy_Goal,
        NPC_GOAL_BPLANKTONFLANK, zNPCGoalBPlanktonFlank::create, GOALDestroy_Goal,
        NPC_GOAL_BPLANKTONEVADE, zNPCGoalBPlanktonEvade::create, GOALDestroy_Goal,
        NPC_GOAL_BPLANKTONHUNT, zNPCGoalBPlanktonHunt::create, GOALDestroy_Goal,
        NPC_GOAL_BPLANKTONTAUNT, zNPCGoalBPlanktonTaunt::create, GOALDestroy_Goal,
        NPC_GOAL_BPLANKTONMOVE, zNPCGoalBPlanktonMove::create, GOALDestroy_Goal,
        NPC_GOAL_BPLANKTONSTUN, zNPCGoalBPlanktonStun::create, GOALDestroy_Goal,
        NPC_GOAL_BPLANKTONFALL, zNPCGoalBPlanktonFall::create, GOALDestroy_Goal,
        NPC_GOAL_BPLANKTONDIZZY, zNPCGoalBPlanktonDizzy::create, GOALDestroy_Goal,
        NPC_GOAL_BPLANKTONBEAM, zNPCGoalBPlanktonBeam::create, GOALDestroy_Goal,
        NPC_GOAL_BPLANKTONWALL, zNPCGoalBPlanktonWall::create, GOALDestroy_Goal,
        NPC_GOAL_BPLANKTONMISSLE, zNPCGoalBPlanktonMissle::create, GOALDestroy_Goal,
        NPC_GOAL_BPLANKTONBOMB, zNPCGoalBPlanktonBomb::create, GOALDestroy_Goal,
        0
    };
    // clang-format on

    fac->RegItemType(typelist);
}