#pragma once

#include "xVec3.h"

enum
{
    k_XENTMOTIONMECH_SLIDE,
    k_XENTMOTIONMECH_ROT,
    k_XENTMOTIONMECH_SLIDE_ROT,
    k_XENTMOTIONMECH_SLIDE_THEN_ROT,
    k_XENTMOTIONMECH_ROT_THEN_SLIDE
};

enum
{
    k_XENTMOTIONMECH_RETURNS = (1 << 0),
    k_XENTMOTIONMECH_ONCE = (1 << 1),
};

enum
{
    k_XENTMOTIONTYPE_ER,
    k_XENTMOTIONTYPE_ORBIT,
    k_XENTMOTIONTYPE_SPLINE,
    k_XENTMOTIONTYPE_MP,
    k_XENTMOTIONTYPE_MECH,
    k_XENTMOTIONTYPE_PEND,
    k_XENTMOTIONTYPE_NONE
};

enum
{
    k_XENTMOTION_0x1 = (1 << 0),
    k_XENTMOTION_STOPPED = (1 << 2)
};
