name: build_pr

on:
  pull_request_target:
    branches: [ master ]

jobs:
  build_pr:
    if: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
    - name: Checkout tools
      uses: actions/checkout@v2
      with:
        repository: mattbruv/bfbb-private
        token: ${{ secrets.PRIVATE_REPO_ACCESS }}
        path: bfbb-tools
    - name: Decrypt tools
      run: echo ${{ secrets.BFBB_TOOLS }} | openssl enc -d -aes-256-cbc -pass stdin -pbkdf2 -in bfbb-tools/bfbb.tar.gz.aes -out bfbb.tar.gz
    - name: Extract tools
      run: tar xvzf bfbb.tar.gz
    - name: Compile
      uses: docker://docker.io/bfbbdecomp/bfbb:latest
      with:
        args: make --jobs
    - name: Clang Format
      uses: docker://docker.io/bfbbdecomp/bfbb:latest
      with:
        args: sh -c "clang-format -i -style=file src/**/*.cpp || echo \"::warning clang-formatter check failed\""
